// questions.js - Trivia Question Bank (5 Questions each per round)

// GULDER ULTIMATE QUESTIONS
const GULDER_QUESTIONS = [
  { q: "In which year did Gulder Ultimate Search first premiere?", options: ["2002", "2003", "2004", "2005"], answer: 2 },
  { q: "Where was Season 1 of Gulder Ultimate Search held?", options: ["Snake Island, Lagos", "Aguleri Forest", "Obudu Hills", "Omo Forest"], answer: 0 },
  { q: "What was the theme of Season 1?", options: ["The Lost Helmet of General Maximilian", "The Brew Master's Secret", "The Search for the Golden Age", "The Legend of Captain Kush"], answer: 3 },
  { q: "Who became the first-ever winner of Gulder Ultimate Search?", options: ["Lucan Chambliss", "Hector Joberteh", "Dominic Mudabai", "Ezeugo (Ugo) Egwuagwu"], answer: 3 },
  { q: "What was the cash prize for the winner of Season 1?", options: ["₦2 Million", "₦3 Million", "₦5 Million", "₦10 Million"], answer: 1 },
  { q: "Which location hosted Season 2?", options: ["Jos", "Usaka", "Obudu Hills, Cross River", "Benin Forest"], answer: 2 },
  { q: "What was the theme of Season 2?", options: ["The Horn of Valour", "The Lost Helmet of General Maximilian", "The General's Helmet", "The Tenth Symbol"], answer: 1 },
  { q: "Who won Season 2?", options: ["Michael Nwachukwu", "Lucan Chambliss", "Dominic Mudabai", "Dennis Okike"], answer: 1 },
  { q: "Which location hosted Season 3?", options: ["Snake Island", "Usaka", "Aguleri", "NIFOR, Benin, Edo State"], answer: 3 },
  { q: "What was the theme of Season 3?", options: ["Contest of Champions", "Ultimate Hero", "The Brew Master's Secret", "Gatekeeper's Fortune"], answer: 2 },
  { q: "Who won Season 3?", options: ["Chris Okagbue", "Uche Nwaezeapu", "Hector Joberteh", "Chinedu Ubachukwu"], answer: 2 },
  { q: "Besides the cash prize, what vehicle did the Season 3 winner receive?", options: ["Ford Explorer SUV", "Mitsubishi Pajero", "Ford Ranger", "Toyota Prado"], answer: 0 },
  { q: "Which state hosted Season 4?", options: ["Enugu", "Ogun", "Plateau State", "Osun"], answer: 2 },
  { q: "Season 4 took place in which hills?", options: ["Kukuruku Hills", "Obudu Hills", "Mambilla Hills", "Shere Hills"], answer: 3 },
  { q: "What was the theme of Season 4?", options: ["Horn of Valour", "The Search for the Golden Age", "The Lost Chronicle", "Ultimate Hero"], answer: 1 },
  { q: "Who won Season 4?", options: ["Michael Nwachukwu", "Dennis Okike", "Dominic Mudabai", "Paschal Eronmose"], answer: 2 },
  { q: "Which unfortunate incident occurred during Season 4?", options: ["A forest fire", "A contestant got lost", "A contestant drowned during filming", "The show was cancelled"], answer: 2 },
  { q: "What was the name of the contestant who drowned during Season 4?", options: ["Hector Joberteh", "Lucan Chambliss", "Dennis Okike", "Anthony Ogadje"], answer: 3 },
  { q: "Gulder Ultimate Search is widely recognized as Nigeria's first:", options: ["Music reality show", "Dance reality show", "Adventure reality television show", "Education reality show"], answer: 2 },
  { q: "Which company created and sponsored Gulder Ultimate Search?", options: ["Guinness Nigeria Plc", "International Breweries Plc", "Nestlé Nigeria Plc", "Nigerian Breweries Plc"], answer: 3 },
  { q: "Which storyline was featured in Gulder Ultimate Search Season 5?", options: ["The Lost Chronicle", "The Horn of Valour", "The Ultimate Hero", "The Tenth Symbol"], answer: 0 },
  { q: "Season 5 of Gulder Ultimate Search was held in:", options: ["Mmaku Hills, Awgu, Enugu State", "Shere Hills, Plateau State", "Kukuruku Hills, Edo State", "Omo Forest, Ogun State"], answer: 0 },
  { q: "Who emerged as the winner of Season 5?", options: ["Michael Nwachukwu", "Dominic Mudabai", "Uche Nwaezeapu", "Chris Okagbue"], answer: 0 },
  { q: "What additional prize did the Season 5 winner receive besides the cash prize?", options: ["Toyota Prado", "Mitsubishi Pajero", "Brand-new SUV", "Ford Ranger"], answer: 2 },
  { q: "Which legendary artifact was contestants searching for in Season 6?", options: ["The Lost Chronicle", "The General's Helmet", "The Horn of Valour", "The Golden Goblet"], answer: 2 },
  { q: "Season 6 was held in:", options: ["Aguleri Forest", "Omo Forest", "Usaka Forest", "Omodo Forest, Aagba, Osun State"], answer: 3 },
  { q: "Who won Gulder Ultimate Search Season 6?", options: ["Dennis Okike", "Kunle Remi", "Michael Nwachukwu", "Uche Nwaezeapu"], answer: 3 },
  { q: "Which special edition of Gulder Ultimate Search was introduced after Season 6?", options: ["Champions Edition", "All-Stars Edition", "Celebrity Showdown", "Legends Edition"], answer: 2 },
  { q: "Who won the Celebrity Showdown edition?", options: ["Emeka Ike", "Richard Mofe-Damijo", "Kanayo O. Kanayo", "Ramsey Nouah"], answer: 0 },
  { q: "What was the name of the treasure in the Celebrity Showdown?", options: ["The Silver Shield", "The Golden Goblet", "The Ancient Scroll", "The King's Sword"], answer: 1 },
  { q: "Which storyline was used in Season 7?", options: ["The Contest of Champions", "The Ultimate Hero", "The Search for the Golden Age", "The Gatekeeper's Fortune"], answer: 1 },
  { q: "Season 7 took place in:", options: ["Omo Forest, Ogun State", "Omodo Forest", "Kukuruku Hills", "Usaka Valley"], answer: 0 },
  { q: "Who won Season 7?", options: ["Chris Okagbue", "Dennis Okike", "Oyekunle Oluwaremi (Kunle Remi)", "Paschal Eronmose"], answer: 2 },
  { q: "Which career did Season 7 winner Kunle Remi become widely known for after GUS?", options: ["Football", "Politics", "Music", "Acting (Nollywood)"], answer: 3 },
  { q: "Which storyline was featured in Season 8?", options: ["The Gatekeeper's Fortune", "The Ultimate Hero", "The Contest of Champions", "The Lost Helmet of General Maximilian"], answer: 2 },
  { q: "Where was Season 8 held?", options: ["Aguleri Forest", "Omo Forest", "Kukuruku Hills, Ososo, Edo State", "Obudu Hills"], answer: 2 },
  { q: "Who emerged as the winner of Season 8?", options: ["Kunle Remi", "Michael Nwachukwu", "Paschal Eronmose", "Chris Okagbue"], answer: 3 },
  { q: "Season 8 was unique because contestants were:", options: ["All celebrities", "Previous champions competing against one another", "All first-time participants", "Only women"], answer: 1 },
  { q: "Chris Okagbue later became well known in:", options: ["Banking", "Law", "Medicine", "Television and Nollywood"], answer: 3 },
  { q: "Which pair correctly matches the season with its storyline?", options: ["Season 5 – The Horn of Valour", "Season 6 – The Ultimate Hero", "Season 7 – The Ultimate Hero", "Season 8 – The Gatekeeper's Fortune"], answer: 2 },
  { q: "Which storyline was featured in Gulder Ultimate Search Season 9?", options: ["The Tenth Symbol", "The General's Helmet", "The Lost Chronicle", "The Gatekeeper's Fortune"], answer: 3 },
  { q: "Season 9 of Gulder Ultimate Search was held in:", options: ["Aguleri Forest, Anambra", "Omo Forest, Ogun", "Usaka, Obot Akara, Akwa Ibom", "Shere Hills, Plateau"], answer: 2 },
  { q: "Who won Gulder Ultimate Search Season 9?", options: ["Paschal Eronmose Ojezele", "Chinedu Ubachukwu", "Chris Okagbue", "Dennis Okike"], answer: 0 },
  { q: "What was the grand cash prize for the Season 9 winner?", options: ["₦9 Million", "₦7 Million", "₦5 Million", "₦10 Million"], answer: 0 },
  { q: "Besides the cash prize, what extra allowance did the Season 9 winner receive?", options: ["₦500,000 Swagger Allowance", "₦1 Million Housing Allowance", "₦750,000 Feeding Allowance", "₦250,000 Travel Allowance"], answer: 0 },
  { q: "Who directed Gulder Ultimate Search Season 9?", options: ["Tade Ogidan", "Kunle Afolayan", "Mildred Okwo", "Laszlo Bene"], answer: 3 },
  { q: "Which storyline was used for Gulder Ultimate Search Season 10?", options: ["The Ultimate Hero", "The Tenth Symbol", "The Gatekeeper's Fortune", "The General's Helmet"], answer: 1 },
  { q: "Season 10 was also held in:", options: ["Omo Forest, Ogun State", "Usaka Forest, Akwa Ibom State", "Obudu Hills", "Aguleri Forest, Anambra State"], answer: 1 },
  { q: "Who won Gulder Ultimate Search Season 10?", options: ["Paschal Eronmose", "Chinedu Ubachukwu", "Dennis Okike", "Michael Nwachukwu"], answer: 2 },
  { q: "Which vehicle did Dennis Okike win together with the cash prize?", options: ["Toyota Prado", "Ford Explorer", "Innoson SUV", "Mitsubishi Pajero"], answer: 3 },
  { q: "How much cash did Dennis Okike receive for winning Season 10?", options: ["₦8 Million", "₦9 Million", "₦10 Million", "₦12 Million"], answer: 2 },
  { q: "Who directed Season 10 of Gulder Ultimate Search?", options: ["Tade Ogidan", "Lancelot Imasuen", "Toka McBaror", "Laszlo Bene"], answer: 3 },
  { q: "What was the storyline for Gulder Ultimate Search Season 11?", options: ["The Lost Helmet of General Maximilian", "The Search for the Golden Age", "The General's Helmet", "The Gatekeeper's Fortune"], answer: 2 },
  { q: "Which forest hosted Season 11?", options: ["Usaka Forest", "Omo Forest", "Omodo Forest", "Aguleri Forest, Anambra State"], answer: 3 },
  { q: "Who emerged as the winner of Gulder Ultimate Search Season 11?", options: ["Dennis Okike", "Paschal Eronmose", "Chris Okagbue", "Chinedu Ubachukwu"], answer: 3 },
  { q: "Which vehicle was presented to the winner of Season 11?", options: ["Ford Explorer", "Toyota Land Cruiser", "Innoson SUV", "Mitsubishi Pajero"], answer: 0 },
  { q: "How much cash did the Season 11 winner receive?", options: ["₦10 Million", "₦9 Million", "₦8 Million", "₦15 Million"], answer: 0 },
  { q: "Which state hosted both Season 9 and Season 10?", options: ["Akwa Ibom State", "Plateau State", "Enugu State", "Edo State"], answer: 0 },
  { q: "Which pair correctly matches the storyline with the winner?", options: ["The Tenth Symbol — Paschal Eronmose", "The Gatekeeper's Fortune — Dennis Okike", "The General's Helmet — Chris Okagbue", "The General's Helmet — Chinedu Ubachukwu"], answer: 3 },
  { q: "Which sequence correctly lists the winners of Seasons 9, 10, and 11?", options: ["Dennis Okike → Chinedu Ubachukwu → Paschal Eronmose", "Chris Okagbue → Dennis Okike → Paschal Eronmose", "Paschal Eronmose → Dennis Okike → Chinedu Ubachukwu", "Chinedu Ubachukwu → Paschal Eronmose → Dennis Okike"], answer: 2 },
  { q: "What was the official theme of Gulder Ultimate Search Season 12?", options: ["The Ultimate Hero", "The Age of Craftsmanship", "The Age of Discovery", "The Return of the Warrior"], answer: 1 },
  { q: "After how many years did Gulder Ultimate Search return to television?", options: ["5 years", "7 years", "6 years", "8 years"], answer: 1 },
  { q: "Who was the official anchor (host) of Season 12?", options: ["Nancy Isime", "Chidi Mokeme", "Stephanie Coker", "Toke Makinwa"], answer: 3 },
  { q: "Who served as the Taskmaster in Season 12?", options: ["Chidi Mokeme", "Bob-Manuel Udokwu", "Richard Mofe-Damijo", "Kunle Remi"], answer: 3 },
  { q: "How many contestants began Season 12?", options: ["16", "20", "18", "24"], answer: 2 },
  { q: "What hidden treasure were contestants searching for?", options: ["The Golden Goblet", "The Lost Helmet", "The Horn of Valour", "Akolo's Chest"], answer: 3 },
  { q: "Who emerged as the winner of Season 12?", options: ["Damola Johnson", "Gerald Odeka", "Esitima Edem", "Odudu Otu"], answer: 3 },
  { q: "Odudu Otu originally entered the competition as a:", options: ["Team Captain", "Returning Champion", "Celebrity Guest", "Wildcard"], answer: 3 },
  { q: "Odudu belonged to which clan in Season 12?", options: ["Baobab", "Iroko", "Bamboo", "Palm"], answer: 1 },
  { q: "Which of these contestants was also a member of the Iroko Clan in Season 12?", options: ["Damola Johnson", "Emmanuel Nnebe", "Jennifer Okorie", "Samson Abah"], answer: 0 },
  { q: "Which contestant was known for discovering three boomerangs?", options: ["Gerald", "Damola", "Esitima", "Mfon"], answer: 2 },
  { q: "Which contestant was considered an early favorite before being evicted?", options: ["Yankari", "Tobechukwu", "Gerald Odeka", "Samuel Ishmael"], answer: 2 },
  { q: "Approximately how many Nigerians applied for Season 12 before the final selection?", options: ["Over 20,000", "10,000", "15,000", "5,000"], answer: 0 },
  { q: "Which vehicle did the winner receive?", options: ["Innoson SUV", "Mitsubishi Pajero", "Ford Explorer", "Toyota Land Cruiser"], answer: 0 },
  { q: "Besides the SUV, what international reward did the winner receive?", options: ["Trip to London", "Trip to Kenya", "Trip to South Africa", "Return ticket to Dubai"], answer: 3 },
  { q: "The total prize package for the winner of Season 12 was worth:", options: ["₦20 million", "₦30 million", "₦40 million", "₦50 million worth of prizes"], answer: 3 },
  { q: "What did Akolo's Chest supposedly contain?", options: ["Ancient gold coins", "The secret of Akolo's legendary brew", "A magic sword", "A royal crown"], answer: 1 },
  { q: "Which company donated the winner's SUV?", options: ["Toyota Nigeria", "Innoson Vehicle Manufacturing", "Mikano Motors", "Coscharis Motors"], answer: 1 },
  { q: "Which of these contestants competed in Season 12?", options: ["Jennifer Okorie", "Chris Okagbue", "Chinedu Ubachukwu", "Dennis Okike"], answer: 0 },
  { q: "Which statement about Season 12 is TRUE?", options: ["The winner was chosen by SMS voting.", "There were only 12 contestants.", "Odudu Otu found Akolo's Chest in the finale to become the Ultimate Man.", "The treasure was called \"The Golden Goblet.\""], answer: 2 },
  { q: "Which season was the first to offer a ₦10 million cash prize?", options: ["Season 8", "Season 9", "Season 10", "Season 11"], answer: 2 },
  { q: "Which winner discovered \"The Tenth Symbol\"?", options: ["Chinedu Ubachukwu", "Paschal Eronmose Ojezele", "Chris Okagbue", "Dennis Okike"], answer: 3 },
  { q: "Which season was held in Aguleri Forest, Anambra State?", options: ["Season 11", "Season 10", "Season 9", "Season 12"], answer: 0 },
  { q: "Which season's treasure was \"The Horn of Valour\"?", options: ["Season 5", "Season 6", "Season 7", "Season 8"], answer: 1 },
  { q: "Which winner later returned as the Taskmaster?", options: ["Chris Okagbue", "Dennis Okike", "Dominic Mudabai", "Kunle Remi"], answer: 3 },
  { q: "Which season was themed \"The Contest of Champions\"?", options: ["Season 6", "Season 7", "Season 8", "Season 9"], answer: 2 },
  { q: "Which season took place at Snake Island, Lagos?", options: ["Season 2", "Season 1", "Season 3", "Season 4"], answer: 1 },
  { q: "Which of these contestants became a successful fitness entrepreneur after winning GUS?", options: ["Dennis Okike", "Dominic Mudabai", "Michael Nwachukwu", "Paschal Eronmose"], answer: 1 },
  { q: "Who found \"The Lost Chronicle\"?", options: ["Michael Nwachukwu", "Chris Okagbue", "Uche Nwaezeapu", "Lucan Chambliss"], answer: 0 },
  { q: "Which season introduced the Celebrity Showdown?", options: ["After Season 6", "After Season 5", "After Season 4", "After Season 7"], answer: 0 },
  { q: "Which Nollywood actor won the Celebrity Showdown?", options: ["Ramsey Nouah", "Richard Mofe-Damijo", "Kanayo O. Kanayo", "Emeka Ike"], answer: 3 },
  { q: "Which of these storylines came first chronologically?", options: ["The Horn of Valour", "The Lost Chronicle", "The Search for the Golden Age", "The Ultimate Hero"], answer: 2 },
  { q: "Which winner discovered Akolo's Chest?", options: ["Chinedu Ubachukwu", "Dennis Okike", "Chris Okagbue", "Odudu Otu"], answer: 3 },
  { q: "Which season was titled \"The Age of Craftsmanship\"?", options: ["Season 10", "Season 11", "Season 12", "Celebrity Showdown"], answer: 2 },
  { q: "Which state hosted both Seasons 9 and 10?", options: ["Edo", "Enugu", "Ogun", "Akwa Ibom"], answer: 3 },
  { q: "Which pair correctly matches a winner with the treasure discovered?", options: ["Paschal Eronmose — The Gatekeeper's Fortune", "Chinedu Ubachukwu — The Tenth Symbol", "Dennis Okike — The Gatekeeper's Fortune", "Michael Nwachukwu — The Brew Master's Secret"], answer: 0 },
  { q: "Which season was hosted in Omo Forest, Ogun State?", options: ["Season 5", "Season 6", "Season 7", "Season 8"], answer: 2 },
  { q: "Which winner received an Innoson SUV as part of the prize package?", options: ["Dennis Okike", "Chinedu Ubachukwu", "Odudu Otu", "Chris Okagbue"], answer: 2 },
  { q: "Arrange these winners in the correct chronological order:", options: ["Paschal Eronmose → Dennis Okike → Chinedu Ubachukwu", "Chinedu Ubachukwu → Dennis Okike → Paschal Eronmose", "Dennis Okike → Paschal Eronmose → Chinedu Ubachukwu", "Dennis Okike → Chinedu Ubachukwu → Paschal Eronmose"], answer: 0 },
  { q: "Which of the following is the correct sequence of the first four GUS storylines?", options: ["Captain Kush → Brew Master's Secret → Lost Helmet → Golden Age", "Legend of Captain Kush → Lost Helmet of General Maximilian → Brew Master's Secret → Search for the Golden Age", "Lost Helmet → Captain Kush → Golden Age → Brew Master's Secret", "Captain Kush → Search for the Golden Age → Lost Chronicle → Brew Master's Secret"], answer: 1 }
];

// GENERAL QUESTIONS
const GENERAL_QUESTIONS = [
  { q: "Which doctrine states that no individual, including government officials, is above the law?", options: ["Separation of Powers", "Rule of Law", "Federalism", "Sovereignty"], answer: 1 },
  { q: "Which institution has the primary responsibility for interpreting a country's constitution?", options: ["Parliament", "Supreme Court", "Electoral Commission", "Cabinet"], answer: 1 },
  { q: "Which document first proclaimed that \"all human beings are born free and equal in dignity and rights\"?", options: ["Geneva Convention", "Magna Carta", "Paris Agreement", "Universal Declaration of Human Rights"], answer: 3 },
  { q: "Which economic term describes a continuous rise in the general price level of goods and services?", options: ["Deflation", "Recession", "Inflation", "Depression"], answer: 2 },
  { q: "Which organization is responsible for setting international labor standards?", options: ["UNESCO", "WHO", "ILO", "IMF"], answer: 2 },
  { q: "Which of these is NOT a characteristic of democracy?", options: ["One-party dictatorship", "Rule of law", "Free elections", "Protection of rights"], answer: 0 },
  { q: "Sustainable development seeks to balance:", options: ["Economic growth, social progress, and environmental protection", "Politics and religion", "Population and migration", "Exports and imports"], answer: 0 },
  { q: "Which court settles legal disputes between sovereign nations?", options: ["International Court of Justice", "International Criminal Court", "European Court", "African Court of Justice"], answer: 0 },
  { q: "Which electoral system awards victory to the candidate with the highest number of votes, even without a majority?", options: ["Proportional Representation", "First-Past-the-Post", "Ranked Choice", "Runoff Voting"], answer: 1 },
  { q: "The Corruption Perceptions Index is published annually by:", options: ["World Bank", "Transparency International", "IMF", "OECD"], answer: 1 },
  { q: "Which of the following is classified as a non-renewable resource?", options: ["Wind", "Solar", "Natural Gas", "Hydropower"], answer: 2 },
  { q: "Which agreement aims to limit global temperature increases due to climate change?", options: ["Paris Agreement", "Kyoto Protocol", "Geneva Protocol", "Montreal Convention"], answer: 0 },
  { q: "In most democratic countries, which arm of government approves the national budget?", options: ["Legislature", "Judiciary", "Executive", "Military"], answer: 0 },
  { q: "A country's central bank primarily regulates:", options: ["Monetary policy", "Tourism", "Agriculture", "Education"], answer: 0 },
  { q: "Life expectancy refers to:", options: ["Average retirement age", "Average working years", "Average marriage age", "Average years a newborn is expected to live"], answer: 3 },
  { q: "Federalism involves:", options: ["One central government only", "Rule by judges", "Division of powers between national and regional governments", "Military leadership"], answer: 2 },
  { q: "Which UN agency focuses specifically on children's welfare?", options: ["FAO", "WHO", "UNICEF", "UNDP"], answer: 2 },
  { q: "Which institution is often referred to as the \"Fourth Estate\"?", options: ["Parliament", "Military", "Media", "Judiciary"], answer: 2 },
  { q: "A judge hearing a case involving a close family member is an example of:", options: ["Conflict of Interest", "Transparency", "Judicial Review", "Accountability"], answer: 0 },
  { q: "Which factor contributes most to rapid urbanization?", options: ["Rural-to-urban migration", "Lower birth rate", "Increased exports", "Desertification alone"], answer: 0 },
  { q: "Which international organization regulates global trade rules?", options: ["WTO", "WHO", "UNESCO", "NATO"], answer: 0 },
  { q: "Which principle prevents one arm of government from becoming too powerful?", options: ["Absolute Rule", "Checks and Balances", "Dictatorship", "Colonialism"], answer: 1 },
  { q: "Which indicator best measures a country's overall economic output?", options: ["CPI", "GDP", "HDI", "FDI"], answer: 1 },
  { q: "The HDI (Human Development Index) combines health, education, and:", options: ["Military strength", "Income", "Religion", "Population"], answer: 1 },
  { q: "Which crime involves obtaining money through deception?", options: ["Fraud", "Assault", "Burglary", "Vandalism"], answer: 0 },
  { q: "Which organization coordinates international public health?", options: ["IAEA", "IMF", "FIFA", "WHO"], answer: 3 },
  { q: "Which of the following is an example of civil disobedience?", options: ["Tax evasion", "Armed robbery", "Terrorism", "Peacefully refusing to obey an unjust law"], answer: 3 },
  { q: "Which document grants a citizen permission to travel internationally?", options: ["Driver's License", "Birth Certificate", "Identity Card", "Passport"], answer: 3 },
  { q: "Which economic condition is characterized by falling prices over time?", options: ["Inflation", "Expansion", "Recession", "Deflation"], answer: 3 },
  { q: "Which factor is most closely associated with social inequality?", options: ["Equal opportunity", "Population growth", "Unequal access to education and income", "Tourism"], answer: 2 },
  { q: "Which branch of government is responsible for implementing laws?", options: ["Executive", "Judiciary", "Legislature", "Electoral Commission"], answer: 0 },
  { q: "Which international organization is headquartered in New York City?", options: ["United Nations", "African Union", "European Union", "ASEAN"], answer: 0 },
  { q: "Which practice best promotes environmental sustainability?", options: ["Deforestation", "Recycling and waste reduction", "Burning plastic waste", "Illegal mining"], answer: 1 },
  { q: "Which concept means citizens have the right to obtain information about government activities?", options: ["Transparency", "Monopoly", "Nepotism", "Immunity"], answer: 0 },
  { q: "Which of these is considered a white-collar crime?", options: ["Armed robbery", "Insider trading", "Kidnapping", "Assault"], answer: 1 },
  { q: "Which factor generally increases a country's labor productivity?", options: ["Political instability", "Higher crime rates", "Poor healthcare", "Better education and skills training"], answer: 3 },
  { q: "Which global goal focuses on ending extreme poverty by 2030?", options: ["Millennium Challenge", "Kyoto Initiative", "Green Deal", "Sustainable Development Goals (SDGs)"], answer: 3 },
  { q: "Which demographic measure compares the number of live births to the total population?", options: ["Mortality Rate", "Birth Rate", "Migration Rate", "Fertility Index"], answer: 1 },
  { q: "Which principle requires public officials to answer for their actions?", options: ["Accountability", "Monopoly", "Privilege", "Immunity"], answer: 0 },
  { q: "Which of the following best defines good governance?", options: ["Government without elections", "Military administration", "Transparent, accountable, effective, and participatory leadership", "One-party rule"], answer: 2 },
  { q: "Which economic system is primarily based on private ownership and free market competition?", options: ["Communism", "Socialism", "Capitalism", "Feudalism"], answer: 2 },
  { q: "Which international organization provides financial assistance to developing countries for development projects?", options: ["FIFA", "NATO", "World Bank", "Interpol"], answer: 2 },
  { q: "Which philosopher is widely associated with the idea of the \"social contract\" in political theory?", options: ["Isaac Newton", "Charles Darwin", "John Locke", "Galileo Galilei"], answer: 2 },
  { q: "Which of the following best describes \"brain drain\"?", options: ["Growth in local industries", "Migration of skilled professionals to other countries", "Increased birth rate", "Rise in inflation"], answer: 1 },
  { q: "Which international organization is responsible for global police cooperation?", options: ["UNESCO", "Interpol", "World Bank", "WTO"], answer: 1 },
  { q: "Which of the following is NOT one of the Sustainable Development Goals (SDGs)?", options: ["Zero Hunger", "Quality Education", "Global Military Expansion", "Climate Action"], answer: 2 },
  { q: "Which factor most directly determines a country's population density?", options: ["Total land area and population", "Number of hospitals", "Literacy rate", "Inflation rate"], answer: 0 },
  { q: "Which institution is primarily responsible for conducting a national census?", options: ["Central Bank", "National Population Commission (or equivalent national census agency)", "Supreme Court", "Ministry of Justice"], answer: 1 },
  { q: "Which of the following is an example of civic participation?", options: ["Selling fake products", "Evading taxes", "Bribing officials", "Attending a town hall meeting"], answer: 3 },
  { q: "Which of the following best describes nepotism?", options: ["Fair recruitment", "Favouring relatives in appointments or employment", "Public accountability", "Equal opportunity"], answer: 1 },
  { q: "Which global institution publishes the annual World Development Report?", options: ["World Bank", "WHO", "UNESCO", "OPEC"], answer: 0 },
  { q: "Which of these is an example of renewable energy?", options: ["Coal", "Kerosene", "Diesel", "Solar Power"], answer: 3 },
  { q: "Which branch of government is responsible for enforcing laws?", options: ["Legislature", "Electoral Commission", "Judiciary", "Executive"], answer: 3 },
  { q: "Which term describes the unlawful use of official power for personal gain?", options: ["Transparency", "Corruption", "Accountability", "Federalism"], answer: 1 },
  { q: "Which demographic factor generally contributes most to population growth?", options: ["High birth rate", "High emigration", "Low life expectancy", "Economic recession"], answer: 0 },
  { q: "Which of the following is considered a constitutional democracy?", options: ["Government operating under a constitution and elected leaders", "Government without elections", "Military dictatorship", "Absolute monarchy"], answer: 0 },
  { q: "Which organization is responsible for promoting international educational, scientific, and cultural cooperation?", options: ["UNESCO", "IMF", "OPEC", "WTO"], answer: 0 },
  { q: "Which economic term describes two consecutive quarters of declining economic activity?", options: ["Inflation", "Recession", "Recovery", "Expansion"], answer: 1 },
  { q: "Which principle allows citizens to criticize government policies without fear of punishment in a democracy?", options: ["Freedom of Expression", "Martial Law", "State Monopoly", "Executive Order"], answer: 0 },
  { q: "Which institution is responsible for prosecuting crimes on behalf of the state in many countries?", options: ["Parliament", "Central Bank", "Ministry of Justice or Public Prosecutor's Office", "National Museum"], answer: 2 },
  { q: "Which factor is most likely to reduce unemployment over time?", options: ["Increased investment in businesses", "Closing industries", "Reducing education", "Higher crime"], answer: 0 },
  { q: "Which type of pollution is caused primarily by excessive noise?", options: ["Water Pollution", "Air Pollution", "Noise Pollution", "Soil Pollution"], answer: 2 },
  { q: "Which concept refers to the movement of people from rural areas to urban centres?", options: ["Urbanization", "Globalization", "Colonization", "Industrialization"], answer: 0 },
  { q: "Which document legally records the birth of a child?", options: ["Passport", "Birth Certificate", "Marriage Certificate", "Driver's License"], answer: 1 },
  { q: "Which international financial institution primarily promotes global monetary stability?", options: ["UNESCO", "FIFA", "WHO", "IMF"], answer: 3 },
  { q: "Which of the following best defines globalization?", options: ["Isolation of countries", "Increasing international interconnectedness of economies, cultures, and societies", "Elimination of governments", "Growth of villages only"], answer: 1 },
  { q: "Which form of government is ruled by a monarch whose powers are limited by a constitution?", options: ["Absolute Monarchy", "Constitutional Monarchy", "Dictatorship", "Military Rule"], answer: 1 },
  { q: "Which organization coordinates international responses to disease outbreaks?", options: ["WHO", "OPEC", "WTO", "AU"], answer: 0 },
  { q: "Which practice best demonstrates accountability in public office?", options: ["Refusing independent audits", "Awarding contracts secretly", "Destroying official records", "Publishing financial reports openly"], answer: 3 },
  { q: "Which type of election is held to fill a vacant political office before the next general election?", options: ["Primary Election", "By-election", "Referendum", "Census"], answer: 1 },
  { q: "Which international agreement is primarily aimed at protecting the ozone layer?", options: ["Paris Agreement", "Montreal Protocol", "Kyoto Protocol", "Geneva Convention"], answer: 1 },
  { q: "Which of the following is a major indicator of human development?", options: ["HDI", "CPI", "GDP Deflator", "Stock Index"], answer: 0 },
  { q: "Which of the following best defines \"civil society\"?", options: ["Voluntary organizations operating independently of government", "Military organizations", "Political parties only", "Government ministries"], answer: 0 },
  { q: "Which body is responsible for making recommendations on global public health emergencies?", options: ["WHO", "UNESCO", "WTO", "FIFA"], answer: 0 },
  { q: "Which factor is most essential for maintaining the rule of law?", options: ["One-Party Rule", "Military Control", "State-Owned Media", "Independent Judiciary"], answer: 3 },
  { q: "Which economic concept describes the total value of goods and services produced within a country's borders in one year?", options: ["GDP", "Inflation", "Deficit", "Tariff"], answer: 0 },
  { q: "Which of these is considered a violation of ethical public service?", options: ["Merit-based promotion", "Accepting bribes", "Following procurement rules", "Declaring assets"], answer: 1 },
  { q: "Which social issue is most directly associated with unequal access to education, healthcare, and employment?", options: ["Industrial Growth", "Urban Planning", "Population Census", "Social Inequality"], answer: 3 },
  { q: "Which of the following best explains \"freedom of association\"?", options: ["The right to form or join groups and organizations", "The right to avoid paying taxes", "The right to ignore laws", "The right to own unlimited land"], answer: 0 },
  { q: "Which of the following is the strongest foundation for a stable and peaceful society?", options: ["Rule of Law, justice, and equal opportunity", "Political intimidation", "Widespread censorship", "Military dominance"], answer: 0 },
  { q: "Which principle requires public officials to explain and justify their decisions to the people?", options: ["Sovereignty", "Accountability", "Federalism", "Nationalism"], answer: 1 },
  { q: "Which international organization was established primarily to maintain international peace and security after World War II?", options: ["African Union", "United Nations", "European Union", "Commonwealth"], answer: 1 },
  { q: "Which economic policy generally aims to reduce inflation by increasing interest rates?", options: ["Expansionary monetary policy", "Trade liberalization", "Fiscal stimulus", "Contractionary monetary policy"], answer: 3 },
  { q: "Which of the following is considered a violation of human rights?", options: ["Freedom of worship", "Free elections", "Arbitrary detention without due process", "Equal access to education"], answer: 2 },
  { q: "Which term describes government spending that exceeds government revenue?", options: ["Budget surplus", "Budget deficit", "Trade surplus", "Fiscal balance"], answer: 1 },
  { q: "Which international organization is responsible for regulating international civil aviation standards?", options: ["ICAO", "FIFA", "WHO", "WTO"], answer: 0 },
  { q: "Which factor contributes most to sustainable economic growth?", options: ["Investment in education and innovation", "Increasing corruption", "Political instability", "Excessive inflation"], answer: 0 },
  { q: "Which of these is an example of a non-governmental organization (NGO)?", options: ["Parliament", "Central Bank", "Supreme Court", "Amnesty International"], answer: 3 },
  { q: "Which demographic indicator measures the number of deaths per 1,000 people in a year?", options: ["Birth Rate", "Migration Rate", "Literacy Rate", "Mortality Rate"], answer: 3 },
  { q: "Which type of government is ruled directly by military leaders?", options: ["Constitutional Monarchy", "Military Junta", "Federal Republic", "Parliamentary Democracy"], answer: 1 },
  { q: "Which international body settles trade disputes between member countries?", options: ["WTO", "UNESCO", "WHO", "OPEC"], answer: 0 },
  { q: "Which of the following best defines \"judicial independence\"?", options: ["Judges obey only politicians.", "Judges make decisions free from outside influence.", "Judges are elected every year.", "Judges control the military."], answer: 1 },
  { q: "Which social problem is most directly linked to a rise in homelessness?", options: ["High unemployment", "Increased rainfall", "Better healthcare", "Population decline"], answer: 0 },
  { q: "Which of the following is a direct tax?", options: ["Customs duty", "Import duty", "Value Added Tax", "Income tax"], answer: 3 },
  { q: "Which principle gives citizens the right to choose their leaders?", options: ["Autocracy", "Oligarchy", "Dictatorship", "Democracy"], answer: 3 },
  { q: "Which organization is known for providing emergency humanitarian assistance worldwide?", options: ["FIFA", "OPEC", "WTO", "International Committee of the Red Cross (ICRC)"], answer: 3 },
  { q: "Which factor is most important in reducing the spread of infectious diseases?", options: ["Vaccination and good hygiene", "Higher taxes", "More highways", "Urban migration"], answer: 0 },
  { q: "Which concept refers to equal treatment regardless of race, gender, religion, or ethnicity?", options: ["Discrimination", "Equality", "Nepotism", "Monopoly"], answer: 1 },
  { q: "Which institution is responsible for creating national monetary policy?", options: ["Ministry of Education", "Central Bank", "Parliament", "Ministry of Agriculture"], answer: 1 },
  { q: "Which of the following best describes \"public accountability\"?", options: ["Government secrecy", "Officials being answerable for their actions", "Military control", "Private ownership"], answer: 1 },
  { q: "Which international day is observed annually on December 10?", options: ["World Health Day", "Earth Day", "Human Rights Day", "World Food Day"], answer: 2 },
  { q: "Which of these is most likely to improve a country's Human Development Index (HDI)?", options: ["Political violence", "Increased corruption", "Better healthcare and education", "Higher unemployment"], answer: 2 },
  { q: "Which practice promotes transparency in government?", options: ["Closed procurement processes", "Secret budgets", "Open access to public records", "Hidden contracts"], answer: 2 },
  { q: "Which of the following best defines social justice?", options: ["Equal access to rights and opportunities", "Rule by the wealthy", "Military administration", "Political favouritism"], answer: 0 },
  { q: "Which organization is responsible for protecting refugees globally?", options: ["UNHCR", "IMF", "OPEC", "NATO"], answer: 0 },
  { q: "Which type of unemployment occurs when workers' skills no longer match available jobs?", options: ["Seasonal unemployment", "Structural unemployment", "Cyclical unemployment", "Frictional unemployment"], answer: 1 },
  { q: "Which of the following best defines \"good citizenship\"?", options: ["Respecting laws and participating in civic duties", "Avoiding elections", "Ignoring public responsibilities", "Breaking traffic laws"], answer: 0 },
  { q: "Which international financial institution provides short-term financial support to countries facing balance-of-payments problems?", options: ["IMF", "WHO", "UNESCO", "AU"], answer: 0 },
  { q: "Which environmental issue is caused mainly by the excessive release of greenhouse gases?", options: ["Volcanic eruptions", "Earthquakes", "Tsunamis", "Global warming"], answer: 3 },
  { q: "Which of the following is a key characteristic of a free press?", options: ["Independence from government censorship", "Government ownership of all media", "Ban on investigative journalism", "Political control of news"], answer: 0 },
  { q: "Which institution is primarily responsible for conducting free and fair elections in many democratic countries?", options: ["Electoral Commission", "Supreme Court", "Central Bank", "Ministry of Finance"], answer: 0 },
  { q: "Which type of government is led by a small group of powerful individuals?", options: ["Democracy", "Oligarchy", "Republic", "Federalism"], answer: 1 },
  { q: "Which of the following best measures income inequality within a country?", options: ["Gini Coefficient", "GDP", "CPI", "HDI"], answer: 0 },
  { q: "Which factor most directly contributes to food security?", options: ["Political instability", "Increased pollution", "Sustainable agricultural production", "Deforestation"], answer: 2 },
  { q: "Which international organization is headquartered in Geneva and focuses on global health?", options: ["WTO", "World Bank", "World Health Organization (WHO)", "OPEC"], answer: 2 },
  { q: "Which principle ensures that government power is divided among different branches to prevent abuse?", options: ["Colonialism", "Monarchy", "Separation of Powers", "Militarism"], answer: 2 },
  { q: "Which of the following best describes an \"interest group\"?", options: ["An organization that seeks to influence public policy without seeking political office", "A military alliance", "A judicial body", "A religious denomination"], answer: 0 },
  { q: "Which of the following is considered a cybercrime?", options: ["Identity theft through online fraud", "Paying taxes", "Registering to vote", "Recycling waste"], answer: 0 },
  { q: "Which demographic trend is associated with an aging population?", options: ["Higher dependency ratio", "Higher birth rate", "Increased infant mortality", "Declining life expectancy"], answer: 0 },
  { q: "Which of the following is the strongest indicator of a society governed by democratic principles?", options: ["Government control of all media without independent oversight", "Military rule with suspended elections", "One political party controlling all institutions", "Regular free and fair elections, an independent judiciary, and protection of fundamental rights"], answer: 3 },
  { q: "What is the supreme law of the Federal Republic of Nigeria?", options: ["Electoral Act", "1999 Constitution of Nigeria (as amended)", "Criminal Code", "National Assembly Act"], answer: 1 },
  { q: "How many states make up the Federal Republic of Nigeria?", options: ["35", "36", "37", "38"], answer: 1 },
  { q: "Nigeria officially became a republic in:", options: ["1957", "1960", "1963", "1966"], answer: 2 },
  { q: "Which city served as Nigeria's capital before Abuja?", options: ["Kaduna", "Ibadan", "Lagos", "Enugu"], answer: 2 },
  { q: "Which arm of government is responsible for interpreting the Constitution in Nigeria?", options: ["Executive", "Legislature", "Judiciary", "Civil Service"], answer: 2 },
  { q: "How many senators make up the Nigerian Senate?", options: ["108", "109", "110", "111"], answer: 1 },
  { q: "Which section of the Nigerian Constitution guarantees Fundamental Human Rights?", options: ["Chapter II", "Chapter IV", "Chapter VI", "Chapter VIII"], answer: 1 },
  { q: "Which institution is responsible for conducting elections in Nigeria?", options: ["EFCC", "CBN", "ICPC", "INEC"], answer: 3 },
  { q: "Which Nigerian agency is primarily responsible for combating financial crimes?", options: ["EFCC", "NDLEA", "NAFDAC", "SON"], answer: 0 },
  { q: "The Nigerian currency is issued by the:", options: ["Ministry of Finance", "Nigerian National Petroleum Company Limited", "Central Bank of Nigeria", "Nigerian Exchange Group"], answer: 2 },
  { q: "Which of these is NOT one of Nigeria's geopolitical zones?", options: ["North Central", "South East", "South Central", "North East"], answer: 2 },
  { q: "Which river is Nigeria's longest?", options: ["River Benue", "River Niger", "Cross River", "Ogun River"], answer: 1 },
  { q: "Nigeria became independent from British colonial rule in:", options: ["1957", "1959", "1960", "1963"], answer: 2 },
  { q: "The motto of Nigeria is:", options: ["Unity and Progress", "Peace, Love and Justice", "Unity and Faith, Peace and Progress", "Together We Prosper"], answer: 2 },
  { q: "Which Nigerian institution regulates commercial banks?", options: ["NDIC", "Central Bank of Nigeria", "SEC", "FIRS"], answer: 1 },
  { q: "Which agency is responsible for food and drug regulation in Nigeria?", options: ["SON", "NAFDAC", "NESREA", "FCCPC"], answer: 1 },
  { q: "Which Nigerian agency is responsible for enforcing laws against drug trafficking?", options: ["DSS", "NDLEA", "FRSC", "NSCDC"], answer: 1 },
  { q: "The headquarters of ECOWAS is located in:", options: ["Abuja, Nigeria", "Accra, Ghana", "Lomé, Togo", "Dakar, Senegal"], answer: 0 },
  { q: "Which of these is Nigeria's highest court?", options: ["Court of Appeal", "Federal High Court", "Supreme Court", "National Industrial Court"], answer: 2 },
  { q: "Nigeria operates which system of government?", options: ["Presidential Federal System", "Parliamentary", "Absolute Monarchy", "Military Rule"], answer: 0 },
  { q: "Which mineral resource is most associated with Zamfara State?", options: ["Coal", "Gold", "Tin", "Limestone"], answer: 1 },
  { q: "Which state is popularly known as the \"Centre of Excellence\"?", options: ["Rivers", "Kano", "Lagos", "Oyo"], answer: 2 },
  { q: "Which Nigerian city is known as the \"Coal City\"?", options: ["Jos", "Enugu", "Makurdi", "Ilorin"], answer: 1 },
  { q: "Which Nigerian state is known as the \"Land of Promise\"?", options: ["Akwa Ibom", "Cross River", "Delta", "Bayelsa"], answer: 0 },
  { q: "Which Nigerian state is known as the \"Sunshine State\"?", options: ["Ondo", "Osun", "Ogun", "Ekiti"], answer: 0 },
  { q: "Which Nigerian agency is responsible for road safety?", options: ["FRSC", "VIO", "NSCDC", "LASTMA"], answer: 0 },
  { q: "Which Nigerian agency is responsible for standardizing products?", options: ["SON", "NAFDAC", "EFCC", "NCC"], answer: 0 },
  { q: "Which of these is Nigeria's national anthem adopted in 2024?", options: ["Arise, O Compatriots", "Great Nation", "Stand Up for Nigeria", "Nigeria, We Hail Thee"], answer: 3 },
  { q: "Which Nigerian institution is responsible for collecting most federal taxes?", options: ["Customs Service", "Federal Inland Revenue Service (FIRS)", "CBN", "EFCC"], answer: 1 },
  { q: "Which Nigerian city is home to the Aso Rock?", options: ["Minna", "Lokoja", "Kaduna", "Abuja"], answer: 3 },
  { q: "Which state is known as the \"Food Basket of the Nation\"?", options: ["Kebbi", "Kaduna", "Niger", "Benue"], answer: 3 },
  { q: "Which Nigerian state is famous for the Olumo Rock tourist attraction?", options: ["Ondo", "Oyo", "Ekiti", "Ogun"], answer: 3 },
  { q: "Which Nigerian agency oversees telecommunications?", options: ["NCC", "NITDA", "NBC", "NERC"], answer: 0 },
  { q: "Which Nigerian state hosts the Obudu Mountain Resort?", options: ["Cross River", "Taraba", "Plateau", "Adamawa"], answer: 0 },
  { q: "Which Nigerian institution prints and mints the country's currency and security documents?", options: ["Nigerian Security Printing and Minting PLC", "Central Bank of Nigeria", "FIRS", "Nigerian Customs Service"], answer: 0 },
  { q: "Which Nigerian state is the largest by land area?", options: ["Taraba", "Borno", "Niger State", "Kaduna"], answer: 2 },
  { q: "Which Nigerian state has the highest number of Local Government Areas?", options: ["Lagos", "Kano", "Katsina", "Oyo"], answer: 1 },
  { q: "Which port is regarded as Nigeria's busiest seaport?", options: ["Apapa Port, Lagos", "Onne Port", "Warri Port", "Calabar Port"], answer: 0 },
  { q: "Which Nigerian agency is responsible for managing the country's immigration system?", options: ["Nigeria Customs Service", "Nigeria Immigration Service (NIS)", "NSCDC", "DSS"], answer: 1 },
  { q: "Which of the following best reflects the constitutional structure of Nigeria?", options: ["A unitary republic with one level of government", "A federal republic with powers shared among the federal, state, and local governments", "A constitutional monarchy", "A confederation of independent states"], answer: 1 },
  { q: "Which Nigerian city is officially recognized as the Federal Capital Territory (FCT)?", options: ["Lagos", "Kaduna", "Abuja", "Lokoja"], answer: 2 },
  { q: "Which Nigerian agency is responsible for consumer protection and competition?", options: ["SON", "FCCPC", "NAFDAC", "EFCC"], answer: 1 },
  { q: "Which Nigerian state is known as the \"Home of Peace and Tourism\"?", options: ["Plateau", "Bauchi", "Nasarawa", "Taraba"], answer: 0 },
  { q: "Which major hydroelectric dam is located on the River Niger?", options: ["Shiroro Dam", "Kainji Dam", "Tiga Dam", "Ikere Gorge Dam"], answer: 1 },
  { q: "Which institution is responsible for auditing the accounts of the Federal Government of Nigeria?", options: ["Accountant-General", "Auditor-General for the Federation", "Central Bank of Nigeria", "Fiscal Responsibility Commission"], answer: 1 },
  { q: "The minimum voting age in Nigeria is:", options: ["16 years", "17 years", "18 years", "21 years"], answer: 2 },
  { q: "Which Nigerian agency is responsible for managing national emergencies and disasters?", options: ["NSCDC", "NEMA", "FRSC", "DSS"], answer: 1 },
  { q: "Which Nigerian university is the country's first university?", options: ["Ahmadu Bello University", "University of Nigeria, Nsukka", "University of Lagos", "University of Ibadan"], answer: 3 },
  { q: "Which Nigerian city is famous for the Argungu Fishing Festival?", options: ["Sokoto", "Katsina", "Kano", "Kebbi (Argungu)"], answer: 3 },
  { q: "Which Nigerian state is renowned for tin mining?", options: ["Plateau", "Edo", "Osun", "Bayelsa"], answer: 0 },
  { q: "Which Nigerian institution is responsible for electricity regulation?", options: ["TCN", "NERC", "NNPC Ltd.", "REA"], answer: 1 },
  { q: "Which Nigerian state is known as the \"Treasure Base of the Nation\"?", options: ["Bayelsa", "Delta", "Rivers", "Akwa Ibom"], answer: 2 },
  { q: "Which Nigerian agency is responsible for protecting national parks?", options: ["National Park Service", "NESREA", "NEMA", "FERMA"], answer: 0 },
  { q: "The Nigerian Coat of Arms features which two animals?", options: ["Lions", "Elephants", "Horses", "Leopards"], answer: 2 },
  { q: "Which Nigerian state is famous for the Osun-Osogbo Sacred Grove?", options: ["Oyo", "Osun", "Ekiti", "Ogun"], answer: 1 },
  { q: "Which river meets the River Niger at Lokoja?", options: ["River Cross", "River Benue", "River Kaduna", "River Sokoto"], answer: 1 },
  { q: "Which Nigerian state is known for the Sukur Cultural Landscape, a UNESCO World Heritage Site?", options: ["Adamawa", "Gombe", "Taraba", "Borno"], answer: 0 },
  { q: "Which Nigerian agency regulates the communications sector?", options: ["NCC", "NBC", "NITDA", "SON"], answer: 0 },
  { q: "Which Nigerian state is home to Zuma Rock?", options: ["Niger State", "Kogi", "Nasarawa", "Kaduna"], answer: 0 },
  { q: "Which Nigerian government agency is responsible for maintaining federal roads?", options: ["NEMA", "FRSC", "FERMA", "TCN"], answer: 2 },
  { q: "Which Nigerian state is known as the \"Confluence State\"?", options: ["Benue", "Kwara", "Niger", "Kogi"], answer: 3 },
  { q: "Which Nigerian institution is responsible for pension regulation?", options: ["NDIC", "SEC", "PENCOM", "FIRS"], answer: 2 },
  { q: "Which Nigerian city is famous for the ancient Kano City Walls?", options: ["Kano", "Zaria", "Katsina", "Sokoto"], answer: 0 },
  { q: "Which Nigerian state hosts the Yankari National Park?", options: ["Plateau", "Gombe", "Bauchi", "Taraba"], answer: 2 },
  { q: "Which Nigerian state is known as the \"Heartbeat of the Nation\"?", options: ["Delta", "Anambra", "Edo", "Imo"], answer: 2 },
  { q: "Which Nigerian agency insures bank deposits?", options: ["NDIC", "CBN", "SEC", "AMCON"], answer: 0 },
  { q: "Which Nigerian state is famous for the Durbar Festival?", options: ["Enugu", "Lagos", "Rivers", "Kano"], answer: 3 },
  { q: "Which Nigerian state is known for the Mambilla Plateau?", options: ["Taraba", "Plateau", "Adamawa", "Gombe"], answer: 0 },
  { q: "Which government body approves constitutional amendments in Nigeria?", options: ["Federal Executive Council", "Supreme Court only", "INEC", "National Assembly and the required number of State Houses of Assembly"], answer: 3 },
  { q: "Which Nigerian state is known as the \"Salt of the Nation\"?", options: ["Imo", "Enugu", "Abia", "Ebonyi"], answer: 3 },
  { q: "Which Nigerian institution regulates the capital market?", options: ["NDIC", "CBN", "FIRS", "Securities and Exchange Commission (SEC)"], answer: 3 },
  { q: "Which Nigerian state is famous for the Awhum Waterfall?", options: ["Anambra", "Enugu", "Ebonyi", "Abia"], answer: 1 },
  { q: "Which Nigerian state is popularly called the \"Centre of Unity\"?", options: ["Nasarawa", "Plateau", "Kaduna", "Niger"], answer: 0 },
  { q: "Which Nigerian state hosts the Ikogosi Warm Springs?", options: ["Osun", "Ekiti", "Ondo", "Ogun"], answer: 1 },
  { q: "Which agency is responsible for collecting customs duties in Nigeria?", options: ["FIRS", "Nigeria Customs Service", "EFCC", "NIS"], answer: 1 },
  { q: "Which Nigerian state is known for the Ogbunike Caves?", options: ["Anambra", "Enugu", "Imo", "Delta"], answer: 0 },
  { q: "Which Nigerian state is home to the National War Museum?", options: ["Rivers", "Imo", "Abia", "Enugu"], answer: 2 },
  { q: "Which Nigerian state is famous for the Erin Ijesha (Olumirin) Waterfalls?", options: ["Ondo", "Ekiti", "Osun", "Oyo"], answer: 2 },
  { q: "Which Nigerian institution has the constitutional authority to remove a President through impeachment?", options: ["National Assembly", "Supreme Court", "INEC", "Council of State"], answer: 0 },
  { q: "Which statement best describes Nigeria's constitutional democracy?", options: ["Nigeria is a federal presidential republic governed by the Constitution, with executive, legislative, and judicial branches sharing powers.", "Nigeria is governed by a hereditary monarch.", "Nigeria operates a one-party political system.", "Nigeria has no written constitution."], answer: 0 }
];

// SPORTS QUESTIONS (Add this if your game requires the 3rd category)
const SPORTS_QUESTIONS = [
  { q: "Which nation became the first African country to reach the FIFA World Cup quarter-finals?", options: ["Cameroon", "Nigeria", "Senegal", "Morocco"], answer: 0 },
  { q: "Which goalkeeper won the inaugural Yashin Trophy in 2019?", options: ["Marc-André ter Stegen", "Jan Oblak", "Alisson Becker", "Ederson"], answer: 2 },
  { q: "Which club did José Mourinho first manage to win the UEFA Champions League?", options: ["Inter Milan", "FC Porto", "Chelsea", "Benfica"], answer: 1 },
  { q: "Which player scored the fastest hat-trick in Premier League history?", options: ["Alan Shearer", "Sadio Mané", "Sergio Agüero", "Robbie Fowler"], answer: 1 },
  { q: "Which country hosted the first-ever Africa Cup of Nations (AFCON) in 1957?", options: ["Sudan", "Egypt", "Ethiopia", "Ghana"], answer: 0 },
  { q: "Which player has scored the most goals in UEFA Champions League history?", options: ["Lionel Messi", "Robert Lewandowski", "Cristiano Ronaldo", "Karim Benzema"], answer: 2 },
  { q: "Which club became the first English team to win the European Cup?", options: ["Manchester United", "Liverpool", "Nottingham Forest", "Aston Villa"], answer: 0 },
  { q: "Who was the captain of Italy when they won the 2006 FIFA World Cup?", options: ["Alessandro Del Piero", "Fabio Cannavaro", "Gianluigi Buffon", "Francesco Totti"], answer: 1 },
  { q: "Which Premier League manager is nicknamed \"The Special One\"?", options: ["Pep Guardiola", "José Mourinho", "Carlo Ancelotti", "Arsène Wenger"], answer: 1 },
  { q: "Which player won the Golden Ball at the 2010 FIFA World Cup?", options: ["Andrés Iniesta", "Wesley Sneijder", "Diego Forlán", "Xavi Hernández"], answer: 2 },
  { q: "Which club won the first UEFA Champions League under its current name in 1992–93?", options: ["Marseille", "AC Milan", "Barcelona", "Ajax"], answer: 0 },
  { q: "Which African country won the AFCON title in 2012?", options: ["Zambia", "Ivory Coast", "Ghana", "Nigeria"], answer: 0 },
  { q: "Who is the only goalkeeper to have won the Ballon d'Or?", options: ["Lev Yashin", "Gianluigi Buffon", "Iker Casillas", "Gordon Banks"], answer: 0 },
  { q: "Which country eliminated Brazil from the 1982 FIFA World Cup?", options: ["Italy", "Argentina", "France", "Germany"], answer: 0 },
  { q: "Which player scored the winning goal in the 1999 UEFA Champions League Final?", options: ["Teddy Sheringham", "Ole Gunnar Solskjær", "David Beckham", "Dwight Yorke"], answer: 1 },
  { q: "Which club is nicknamed \"The Old Lady\"?", options: ["Juventus", "AC Milan", "Inter Milan", "Lazio"], answer: 0 },
  { q: "Which nation won the first-ever UEFA European Championship in 1960?", options: ["Soviet Union", "Spain", "France", "Yugoslavia"], answer: 0 },
  { q: "Which player has made the most Premier League appearances?", options: ["Ryan Giggs", "Gareth Barry", "Frank Lampard", "James Milner"], answer: 1 },
  { q: "Which manager won the UEFA Champions League with both Porto and Inter Milan?", options: ["José Mourinho", "Carlo Ancelotti", "Pep Guardiola", "Ottmar Hitzfeld"], answer: 0 },
  { q: "Which player scored the famous \"Goal of the Century\" at the 1986 FIFA World Cup?", options: ["Pelé", "Diego Maradona", "Michel Platini", "Gary Lineker"], answer: 1 },
  { q: "Which player scored the first-ever golden goal in FIFA World Cup history?", options: ["Laurent Blanc", "Dennis Bergkamp", "Roberto Baggio", "Hristo Stoichkov"], answer: 0 },
  { q: "Which club did Cristiano Ronaldo score his 100th UEFA Champions League goal against?", options: ["Bayern Munich", "Juventus", "Atlético Madrid", "Borussia Dortmund"], answer: 0 },
  { q: "Which country won the FIFA World Cup without conceding a single goal in open play?", options: ["Italy (2006)", "Spain (2010)", "Germany (2014)", "Brazil (2002)"], answer: 0 },
  { q: "Who was the youngest player to score in a FIFA World Cup Final?", options: ["Kylian Mbappé", "Pelé", "Lionel Messi", "Michael Owen"], answer: 1 },
  { q: "Which manager led Greece to victory at UEFA Euro 2004?", options: ["Otto Rehhagel", "Guus Hiddink", "Luiz Felipe Scolari", "Dick Advocaat"], answer: 0 },
  { q: "Which African nation was the first to qualify for the FIFA World Cup?", options: ["Egypt", "Morocco", "Tunisia", "Nigeria"], answer: 0 },
  { q: "Which club defeated AC Milan on penalties in the 2005 UEFA Champions League Final after coming back from 3–0 down?", options: ["Liverpool", "Barcelona", "Manchester United", "Chelsea"], answer: 0 },
  { q: "Which player won the Golden Boot at the 1994 FIFA World Cup?", options: ["Hristo Stoichkov", "Romário", "Roberto Baggio", "Oleg Salenko"], answer: 3 },
  { q: "Which two players shared the Golden Boot at the 1994 FIFA World Cup?", options: ["Romário & Roberto Baggio", "Hristo Stoichkov & Oleg Salenko", "Jürgen Klinsmann & Hristo Stoichkov", "Bebeto & Romário"], answer: 1 },
  { q: "Which club won the inaugural Premier League title in 1992–93?", options: ["Manchester United", "Blackburn Rovers", "Arsenal", "Liverpool"], answer: 0 },
  { q: "Which goalkeeper has the most clean sheets in Premier League history?", options: ["Petr Čech", "David Seaman", "Edwin van der Sar", "Pepe Reina"], answer: 0 },
  { q: "Which player scored the winning goal for Spain in the 2010 FIFA World Cup Final?", options: ["David Villa", "Xavi Hernández", "Andrés Iniesta", "Fernando Torres"], answer: 2 },
  { q: "Which country won the AFCON title in 1994?", options: ["Nigeria", "Zambia", "Ghana", "Cameroon"], answer: 0 },
  { q: "Which manager won three consecutive Premier League titles with Manchester United from 1999–2001?", options: ["Sir Alex Ferguson", "Arsène Wenger", "José Mourinho", "Carlo Ancelotti"], answer: 0 },
  { q: "Which player has the most assists in Premier League history?", options: ["Ryan Giggs", "Cesc Fàbregas", "Frank Lampard", "Kevin De Bruyne"], answer: 0 },
  { q: "Which country hosted the first FIFA Women's World Cup in 1991?", options: ["China", "Sweden", "United States", "Norway"], answer: 0 },
  { q: "Which African player became the first to win the UEFA Champions League as captain?", options: ["Samuel Eto'o", "Riyad Mahrez", "Sadio Mané", "None of the above"], answer: 3 },
  { q: "Which team ended Arsenal's 49-match unbeaten Premier League run?", options: ["Manchester United", "Chelsea", "Liverpool", "Blackburn Rovers"], answer: 0 },
  { q: "Which player scored the only goal in the 2002 FIFA World Cup Final?", options: ["Ronaldo Nazário", "Rivaldo", "Ronaldinho", "None of the above"], answer: 3 },
  { q: "Which nation won the first FIFA Confederations Cup under that name in 1997?", options: ["Brazil", "France", "Saudi Arabia", "Argentina"], answer: 0 },
  { q: "Which player scored the fastest goal in FIFA World Cup history?", options: ["Hakan Şükür", "Miroslav Klose", "Ronaldo Nazário", "Pelé"], answer: 0 },
  { q: "Which country was the first to win the FIFA World Cup outside its own continent?", options: ["Brazil", "Argentina", "Italy", "Germany"], answer: 0 },
  { q: "Who was the first footballer to win three FIFA World Cups as a player?", options: ["Diego Maradona", "Pelé", "Cafu", "Garrincha"], answer: 1 },
  { q: "Which club won the UEFA Champions League without losing a single match in the 2007–08 season?", options: ["Manchester United", "Barcelona", "Chelsea", "AC Milan"], answer: 0 },
  { q: "Which player is the only footballer to have won the UEFA Champions League with Ajax, Real Madrid, and AC Milan?", options: ["Samuel Eto'o", "Didier Drogba", "Clarence Seedorf", "Yaya Touré"], answer: 2 },
  { q: "Which goalkeeper captained Spain to their 2010 FIFA World Cup victory?", options: ["Víctor Valdés", "Iker Casillas", "Pepe Reina", "David de Gea"], answer: 1 },
  { q: "Which country won the 2013 Africa Cup of Nations (AFCON)?", options: ["South Africa", "Nigeria", "Ghana", "Ivory Coast"], answer: 1 },
  { q: "Which player scored the winning penalty for Italy in the shootout of the 2006 FIFA World Cup Final?", options: ["Andrea Pirlo", "Fabio Grosso", "Francesco Totti", "Alessandro Del Piero"], answer: 1 },
  { q: "Which Premier League club is nicknamed \"The Toffees\"?", options: ["Everton", "Leicester City", "Aston Villa", "West Ham United"], answer: 0 },
  { q: "Which manager won the UEFA Champions League with both AC Milan and Real Madrid?", options: ["José Mourinho", "Carlo Ancelotti", "Fabio Capello", "Vicente del Bosque"], answer: 1 },
  { q: "Which player scored in three different UEFA Champions League finals for Real Madrid?", options: ["Cristiano Ronaldo", "Raúl González", "Karim Benzema", "Gareth Bale"], answer: 0 },
  { q: "Which country eliminated Nigeria from the 1994 FIFA World Cup?", options: ["Italy", "Brazil", "Bulgaria", "Spain"], answer: 0 },
  { q: "Which player is the all-time top scorer in Africa Cup of Nations history?", options: ["Didier Drogba", "Samuel Eto'o", "Asamoah Gyan", "Rashidi Yekini"], answer: 1 },
  { q: "Which country became the first FIFA World Cup host nation to be eliminated in the group stage?", options: ["South Africa (2010)", "Japan", "Qatar", "Germany"], answer: 0 },
  { q: "Which stadium hosted the 2014 FIFA World Cup Final?", options: ["Maracanã Stadium", "Estádio Nacional", "Mineirão", "Arena Corinthians"], answer: 0 },
  { q: "Which football legend is nicknamed \"Il Fenomeno\"?", options: ["Ronaldinho", "Ronaldo Nazário", "Roberto Carlos", "Romário"], answer: 1 },
  { q: "Which club won the first English Premier League title after the league was formed in 1992?", options: ["Manchester United", "Blackburn Rovers", "Arsenal", "Liverpool"], answer: 0 },
  { q: "Which referee officiated the 2010 FIFA World Cup Final between Spain and the Netherlands?", options: ["Howard Webb", "Pierluigi Collina", "Mark Clattenburg", "Björn Kuipers"], answer: 0 },
  { q: "Which country won the 1996 Africa Cup of Nations?", options: ["South Africa", "Zambia", "Nigeria", "Cameroon"], answer: 0 },
  { q: "Which player won the FIFA World Cup Golden Ball in 2014?", options: ["Thomas Müller", "Lionel Messi", "James Rodríguez", "Arjen Robben"], answer: 1 },
  { q: "Which country was the first to successfully defend the FIFA World Cup title?", options: ["Italy", "Uruguay", "Brazil", "Germany"], answer: 0 },
  { q: "Which player was the first to score in three different FIFA World Cup tournaments?", options: ["Pelé", "Miroslav Klose", "Uwe Seeler", "Cristiano Ronaldo"], answer: 0 },
  { q: "Which club was the first to successfully retain the UEFA Champions League title in the modern Champions League era (since 1992)?", options: ["Barcelona", "AC Milan", "Real Madrid", "Bayern Munich"], answer: 2 },
  { q: "Which nation won the 1976 Africa Cup of Nations, the only edition decided by a final group instead of a knockout final?", options: ["Morocco", "Nigeria", "Egypt", "Ghana"], answer: 0 },
  { q: "Which player scored the third goal for France in the 1998 FIFA World Cup Final against Brazil?", options: ["Emmanuel Petit", "Zinedine Zidane", "Thierry Henry", "David Trezeguet"], answer: 0 },
  { q: "Which manager won the UEFA Champions League with both Borussia Dortmund and Bayern Munich?", options: ["Ottmar Hitzfeld", "Jupp Heynckes", "Carlo Ancelotti", "Pep Guardiola"], answer: 0 },
  { q: "Which goalkeeper won the Golden Glove at the 2014 FIFA World Cup?", options: ["Manuel Neuer", "Keylor Navas", "Tim Howard", "Julio César"], answer: 0 },
  { q: "Which African nation has appeared in the FIFA World Cup the most times?", options: ["Nigeria", "Cameroon", "Ghana", "Morocco"], answer: 1 },
  { q: "Which Premier League player scored five goals in a single match in just 20 minutes?", options: ["Jermain Defoe", "Dimitar Berbatov", "Sergio Agüero", "Alan Shearer"], answer: 2 },
  { q: "Which club won the first-ever European Cup in 1956?", options: ["Real Madrid", "Stade de Reims", "Benfica", "AC Milan"], answer: 0 },
  { q: "Which African player became the first to win the European Cup/UEFA Champions League?", options: ["Rabah Madjer", "George Weah", "Samuel Eto'o", "Abedi Pelé"], answer: 0 },
  { q: "Which player has made the most appearances in FIFA World Cup history?", options: ["Lothar Matthäus", "Lionel Messi", "Cristiano Ronaldo", "Paolo Maldini"], answer: 1 },
  { q: "Which country defeated Ghana on penalties to win the 2015 Africa Cup of Nations?", options: ["Ivory Coast", "Algeria", "Nigeria", "Cameroon"], answer: 0 },
  { q: "Which player was the first to score 50 UEFA Champions League goals?", options: ["Raúl González", "Lionel Messi", "Cristiano Ronaldo", "Ruud van Nistelrooy"], answer: 0 },
  { q: "Which club won the Premier League title with the fewest points in the 38-match era?", options: ["Leicester City", "Manchester United", "Arsenal", "Manchester United (1996–97)"], answer: 3 },
  { q: "Which nation won the FIFA World Cup after losing its opening match of the tournament?", options: ["Spain (2010)", "Argentina (2022)", "Both Spain and Argentina", "Brazil (2002)"], answer: 2 },
  { q: "Who scored Barcelona's winning goal in the 2006 UEFA Champions League Final against Arsenal?", options: ["Ronaldinho", "Samuel Eto'o", "Juliano Belletti", "Ludovic Giuly"], answer: 2 },
  { q: "Which country has won the most Africa Cup of Nations (AFCON) titles?", options: ["Cameroon", "Egypt", "Ghana", "Nigeria"], answer: 1 },
  { q: "Which manager guided Arsenal to their first Premier League title under the Premier League era?", options: ["George Graham", "Arsène Wenger", "Unai Emery", "Mikel Arteta"], answer: 1 },
  { q: "Which player won both the Golden Boot and the Golden Ball at the same FIFA World Cup tournament?", options: ["Mario Kempes (1978)", "Ronaldo Nazário (2002)", "Lionel Messi (2014)", "Paolo Rossi (1982)"], answer: 0 },
  { q: "Which player became the first footballer to score in five different FIFA World Cup tournaments?", options: ["Lionel Messi", "Cristiano Ronaldo", "Miroslav Klose", "Pelé"], answer: 1 },
  { q: "Which country won the first FIFA World Cup held in Asia (2002)?", options: ["Brazil", "Germany", "Turkey", "South Korea"], answer: 0 },
  { q: "Which player scored the fastest goal in UEFA Champions League Final history?", options: ["Paolo Maldini", "Lionel Messi", "Cristiano Ronaldo", "Samuel Eto'o"], answer: 0 },
  { q: "Which club became the first to win the European Cup five times?", options: ["Liverpool", "Real Madrid", "AC Milan", "Bayern Munich"], answer: 1 },
  { q: "Which African player won the UEFA Champions League with both Barcelona and Inter Milan?", options: ["Didier Drogba", "Samuel Eto'o", "Michael Essien", "Yaya Touré"], answer: 1 },
  { q: "Which country defeated Brazil 3–0 in the 1998 FIFA World Cup Final?", options: ["Germany", "France", "Italy", "Netherlands"], answer: 1 },
  { q: "Which player holds the record for the most goals scored in a single FIFA World Cup tournament?", options: ["Just Fontaine", "Gerd Müller", "Ronaldo Nazário", "Miroslav Klose"], answer: 0 },
  { q: "Which manager guided Leicester City to their historic 2015–16 Premier League title?", options: ["Brendan Rodgers", "Nigel Pearson", "Claudio Ranieri", "Martin O'Neill"], answer: 2 },
  { q: "Which country has finished as runners-up in the FIFA World Cup the most times?", options: ["Germany", "Argentina", "Netherlands", "Italy"], answer: 0 },
  { q: "Which player scored the go-ahead goal for Real Madrid in extra time during the 2014 UEFA Champions League Final?", options: ["Sergio Ramos", "Gareth Bale", "Cristiano Ronaldo", "Marcelo"], answer: 1 },
  { q: "Which country won the 2019 Africa Cup of Nations (AFCON)?", options: ["Algeria", "Senegal", "Nigeria", "Egypt"], answer: 0 },
  { q: "Which goalkeeper captained Germany to victory at the 2014 FIFA World Cup?", options: ["Oliver Kahn", "Jens Lehmann", "Manuel Neuer", "Roman Weidenfeller"], answer: 2 },
  { q: "Which player was the first to score 100 UEFA Champions League goals?", options: ["Lionel Messi", "Cristiano Ronaldo", "Raúl González", "Robert Lewandowski"], answer: 1 },
  { q: "Which club completed the famous comeback against Bayern Munich to win the 1999 UEFA Champions League Final?", options: ["Juventus", "Manchester United", "Barcelona", "AC Milan"], answer: 1 },
  { q: "Which player scored the famous \"Hand of God\" goal during the 1986 FIFA World Cup quarter-final against England?", options: ["Pelé", "Diego Maradona", "Zico", "Jorge Valdano"], answer: 1 },
  { q: "Which African nation became the first to host the FIFA World Cup?", options: ["Egypt", "Morocco", "South Africa", "Nigeria"], answer: 2 },
  { q: "Which player has provided the most assists in UEFA Champions League history?", options: ["Lionel Messi", "Ángel Di María", "Cristiano Ronaldo", "Xavi Hernández"], answer: 2 },
  { q: "Which manager has won the most UEFA Champions League/European Cup titles?", options: ["Pep Guardiola", "Carlo Ancelotti", "Bob Paisley", "Zinedine Zidane"], answer: 1 },
  { q: "Who captained Liverpool during the famous \"Miracle of Istanbul\" comeback in the 2005 UEFA Champions League Final?", options: ["Jamie Carragher", "Steven Gerrard", "Sami Hyypiä", "Xabi Alonso"], answer: 1 },
  { q: "Which country became the first African nation to reach the FIFA World Cup semi-finals?", options: ["Cameroon", "Ghana", "Nigeria", "Morocco"], answer: 3 }
];

// expose for legacy scripts
if (typeof window !== "undefined") window.GULDER_QUESTIONS = GULDER_QUESTIONS;


